{% set name = "pyTsetlinMachine" %}
{% set version = "0.4.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyTsetlinMachine-{{ version }}.tar.gz
  sha256: 029ccf448265aa92ee3470b7145698648ceefb69195fd4e20ac30d0230b65bc3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pyTsetlinMachine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cair/pyTsetlinMachine/
  summary: Implements the Tsetlin Machine, Convolutional Tsetlin Machine, Regression Tsetlin Machine, and Weighted Tsetlin Machine, with support for continuous features, multigranularity, and clause indexing.
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - andife
